//File generated by DS-Servers
//Visit https://ds-servers.com
//Download this map: https://ds-servers.com/maps/goldsrc/cstrike/jail_czone.html
gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
models/player/gsg9/gsg9.mdl
models/player/guerilla/guerilla.mdl
overviews/jail_czone.txt
sound/jail_czone/birds.wav
sound/jail_czone/hardstyle.wav
maps/jail_czone.bsp
